# Generated by Django 4.0.1 on 2022-01-17 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_deatured_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='deatured_image',
            new_name='featured_image',
        ),
    ]
